### your site title here

title: Jonas - Persönlicher Blog!
baseurl: http://jonas.mvbuddies.de/blog # name of the repository
#email: your@email.com

timezone: Europe/Berlin

permalink: /:title/

highlighter: rouge
markdown: kramdown


paginate: 4

auto: true




# Tracker
analytics:

# Comments
disqus-shortname: mvbuddies


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
 style: compressed

exclude:
- README.md

timezone: Europe/Berlin



plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
